#!/usr/bin/env bash
yay
yay -S alacritty neovim spotify slack-desktop i3 wl-clipboard github-cli-git ttf-apple-emoji ttf-hack-nerd ttf-hack-nerd ttf-hack-nerd pamixer picom rofi pulseaudio-bluetooth gnome-screenshot dunst cronie acpi autotiling gnome-keyring nautilus rofi-emoji wtype xdotool-git lazygit git-delta network-manager-applet nitrogen
