#!/usr/bin/env bash

# Run Scripts
./install_and_configure_yay
./install_yay_packages

# Move Configs into Right Places
sudo cp -a ../.zshrc ~
sudo cp -a ../.gitconfig ~
sudo cp -a ../.config/. ~/.config
sudo cp -a ../.local/. ~/.local
sudo cp -a ../share/. /usr/share/
sudo cp -a ../.gnupg/ ~/.config

# Lockscreen
betterlockscreen -u ~/Pictures/lockscreen.jpg

# Auto CPU Frequency
systemctl enable --now auto-cpufreq.service

# Install Node Version Manager
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash

zsh
nvim
